# Generated by Django 6.1 on 2026-09-02 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('supported', 'Supported'), ('contradicted', 'Contradicted'), ('partially_supported', 'Partially Supported'), ('uncertain', 'Uncertain')], default='pending', max_length=40)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_from_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='notes.note')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('official', 'Official'), ('academic', 'Academic'), ('educational', 'Educational'), ('community', 'Community'), ('user', 'User'), ('other', 'Other')], default='other', max_length=30)),
                ('access_method', models.CharField(blank=True, max_length=100)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('license_url', models.URLField(blank=True)),
                ('attribution_required', models.BooleanField(default=False)),
                ('commercial_use_allowed', models.BooleanField(default=False)),
                ('ai_use_allowed', models.BooleanField(default=False)),
                ('scraping_allowed', models.BooleanField(default=False)),
                ('api_available', models.BooleanField(default=False)),
                ('authority_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('related', 'Related')], default='related', max_length=30)),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences_items', to='knowledge.claim')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='knowledge.source')),
            ],
            options={
                'ordering': ['relevance_score', '-created_at'],
            },
        ),
    ]
