# Generated by Django 6.1 on 2026-09-04 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_concept_extractedclaim_canonicalclaim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='knowledge.extractedclaim'),
        ),
    ]
