# Generated by Django 6.1 on 2026-09-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_evidence_claim'),
        ('learning', '0003_alter_flashcard_source_claim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
