# Generated by Django 6.1 on 2026-09-09 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_delete_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmappedConceptReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_name', models.CharField(max_length=255)),
                ('context_text', models.TextField(help_text='Snippet of text where the term was found')),
                ('status', models.CharField(choices=[('pending', 'Pending Developer Review'), ('approved', 'Approved & Added to Taxonomy'), ('rejected', 'Rejected / Not a Valid Concept')], default='pending', max_length=30)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmapped_reviews', to='knowledge.extractedclaim')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_concepts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('parent', 'Parent'), ('related', 'Related'), ('implements', 'Implements'), ('builds_on', 'Builds On'), ('used_by', 'Used By'), ('alternative', 'Alternative')], default='related', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='knowledge.concept')),
                ('to_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='knowledge.concept')),
            ],
            options={
                'ordering': ['from_concept__name'],
                'unique_together': {('from_concept', 'to_concept', 'relation_type')},
            },
        ),
    ]
