# Generated by Django 6.1 on 2026-09-26 11:33

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension



class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_unmappedconceptreview_conceptrelationship'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='evidence',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
