# Generated by Django 6.1 on 2026-09-03 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploaded', 'Pending'), ('processing', 'Processing'), ('ocr_done', 'OCR Done'), ('claims_extracted', 'Claims Extracted'), ('verified', 'Verified'), ('failed', 'Failed')], default='uploaded', max_length=40)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_job', to='notes.note')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
