# Generated by Django 6.1 on 2026-09-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteprocessingjob',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noteprocessingjob',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
