# Generated by Django 6.1 on 2026-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='created_by',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='understood_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
