# Generated by Django 6.1 on 2026-09-03 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_concept_extractedclaim_canonicalclaim_and_more'),
        ('learning', '0002_alter_flashcard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='source_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='knowledge.canonicalclaim'),
        ),
    ]
