# Generated by Django 6.1 on 2026-10-03 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_evidence_embedding'),
        ('learning', '0004_playlist_playlistitem_delete_savedflashcard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')])),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('passing_threshold', models.PositiveSmallIntegerField(default=8)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='knowledge.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('options', models.JSONField(help_text='List of 4 string options')),
                ('correct_option_index', models.PositiveSmallIntegerField(help_text='Index 0-3 of the correct option')),
                ('explanation', models.TextField(blank=True)),
                ('user_selected_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('flashcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_questions', to='learning.flashcard')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='MasteryBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superset', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('difficult_progression', models.JSONField(default=dict, help_text='Log of completed tiers, scores, and dates')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_badges', to='knowledge.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completion_date'],
                'unique_together': {('user', 'concept')},
            },
        ),
    ]
