# Generated by Django 6.1 on 2026-09-02 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_provider', models.CharField(choices=[('django', 'Django'), ('google', 'Google')], default='django', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('education_level', models.CharField(blank=True, max_length=255)),
                ('learning_goal', models.CharField(blank=True, max_length=255)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('profile_completed', models.BooleanField(default=False)),
                ('google_picture_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
