# Generated by Django 6.1 on 2026-09-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_view_own_notes',
            field=models.BooleanField(default=False),
        ),
    ]
